sudo: required
services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main'
        key_url: 'https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub'
    packages:
        - salt-common

stages:
  - validation
  - delivery
  - submit

jobs:
  include:
    - stage: validation
      script:
        - |
          # validate states
          ci/validate-formula.sh

    - stage: delivery
      if: type != pull_request
      env:
        - FOLDER=/package
        - PACKAGE_NAME=habootstrap-formula

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" \
          -e OBS_USER=$OBS_USER \
          -e OBS_PASS=$OBS_PASS \
          -e FOLDER=$FOLDER \
          -e OBS_PROJECT=$OBS_PROJECT \
          -e PACKAGE_NAME=$PACKAGE_NAME \
          shap/continuous_deliver \
          /bin/bash -c "cd /package;/scripts/upload.sh"

    - stage: submit
      if: type != pull_request AND branch = master
      env:
        - PACKAGE_NAME=habootstrap-formula

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" \
          -e OBS_USER=$OBS_USER \
          -e OBS_PASS=$OBS_PASS \
          -e OBS_PROJECT=$OBS_PROJECT \
          -e PACKAGE_NAME=$PACKAGE_NAME \
          -e TARGET_PROJECT=$TARGET_PROJECT \
          shap/continuous_deliver \
          /bin/bash -c "cd /package;/scripts/submit.sh"
